<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Alphabet.Modules.SystemLogModule</AssemblyName>
    <RootNamespace>Alphabet.Modules.SystemLogModule</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Libraries\Alphabet.Common\Alphabet.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Mvc" Version="8.1.1" />
  </ItemGroup>
</Project>
